/* ============================================================
   DROOOLY — the wheel builder

   Price Designs sells seven configurators: the 17x9 truck, Pro R / Turbo R,
   Maverick R, X3, RZR, Expedition and the sand car. This is all seven, on our
   site, in our language — with a live render that recomposites as you choose,
   and with the one thing his cannot do, because we already know the customer's
   truck.

   SPEC-DRIVEN. Every step, option, price, rule and layer comes from
   window.BUILDERS (generated by tools/scrape-price-designs.js from his own
   builder config, then compiled by tools/build-builders.js). There is no
   product knowledge in this file. An eighth platform is another JSON file,
   not another engine.

   ------------------------------------------------------------------
   THE THREE THINGS THAT ARE NOT OBVIOUS
   ------------------------------------------------------------------

   1. A HIDDEN STEP HOLDS NO ANSWER, and visible() iterates to a fixed point to
      enforce it. Choose HALO, answer HALO RING FINISH, then switch back to
      SAWBLADE: the halo finish step goes away, and if its answer survived it
      would keep firing the rules other steps hang off — POST-CUT HALO RING?
      would stay open on a wheel with no halo ring, and its layer would stay in
      the render. Clearing can itself un-hide a step, which can hide another,
      so one pass is not enough. It always terminates: each pass only deletes,
      so the answer set shrinks monotonically.

      EVERYTHING downstream reads the EFFECTIVE pick that visible() returns,
      never S.pick — the price, the summary, the readout, the layers and the
      saved build. S.pick is only what the customer has clicked; it may hold
      answers to steps that are not currently on the page, and it must, because
      flipping back to HALO should restore the finish they already chose.

   2. LAYERS ARE SWAPPED, NEVER RE-SRC'd. Setting .src on a live <img> blanks
      it until the new file decodes, so a colour change would flash the wheel
      away and back. Instead each step owns an <img>, and a change builds a NEW
      one off-screen and only swaps it in once it has loaded. The old layer
      stays visible the whole time, so the wheel never flickers — it just
      becomes the new colour. See paintLayers().

   3. THE RENDER IS HIS ARTWORK, SERVED FROM HIS CDN. 1,542 layer renders is
      ~100MB; we reference them by filename against SPEC.layerBase rather than
      copying them into the repo. tools/mirror-pd-art.js localises the lot and
      rewrites layerBase in one command. LAUNCH-CHECKLIST 1.13 and 4.42.

   WHY A WHOLESALE RE-RENDER of the controls. render() rebuilds every control
   from state rather than patching the one that changed, because which steps
   exist at all is derived from the answers. ~20 steps is nothing to rebuild.
   THE ONE EXCEPTION is the notes textarea: a rebuild would destroy the caret
   mid-sentence, so it is built once and skipped by render(). Do not
   "simplify" it back into the loop.
   ============================================================ */
(function () {
  var root = document.getElementById("builderPage");
  if (!root) return;

  /* A MISSING SCRIPT MUST NOT LEAVE A BLANK PAGE. This used to `return` when
     either dependency was absent, which is right for a page where the module
     is an enhancement — and wrong here, where it IS the page. One dropped
     request for builders-data.js or builder-logic.js and the customer gets an
     empty white screen with no way forward and nothing to report.

     Seen for real: the dev server dropped builder-logic.js under parallel
     requests and the chooser rendered nothing at all. Rare in production
     behind a CDN, but "rare" and "silent" is the combination worth spending
     eight lines on. */
  if (!window.BUILDERS || !window.BuilderLogic) {
    root.innerHTML =
      '<section class="vizhead">' +
        '<p class="kicker"><b>Price Designs</b></p>' +
        "<h1>The builder didn’t load</h1>" +
        '<p class="vizhead__lead">Something dropped on the way in — a reload usually ' +
          "fixes it. If it doesn’t, we’ll build it with you over the phone.</p>" +
        '<p class="vizhead__back">' +
          '<a class="blink" href="' + location.pathname + location.search + '">Try again</a>' +
          ' · <a class="blink" href="tel:+16023325400">(602) 332-5400</a>' +
          ' · <a class="blink" href="shop.html?brand=price-designs">Browse the wheels</a>' +
        "</p>" +
      "</section>";
    return;
  }

  /* The page field is painted on <body>, not on this element: .vizpage is the
     <main> and is capped at --max, so a texture set here would render as a
     1280px column of pattern with bare white either side of it. */
  document.body.classList.add("builder-page");

  var q = new URLSearchParams(location.search);
  var SPEC = window.BUILDERS[q.get("b")];

  /* ---- tiny helpers --------------------------------------------------- */
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function money(n) { return "$" + Number(n).toLocaleString("en-US"); }
  function slug(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

  /* ================================================================
     NO ?b= — the platform picker.

     His site asks which machine you are building for before it asks anything
     else, and so does ours. The cards come straight off the specs, so an
     eighth platform needs no edit here.
     ================================================================ */
  if (!SPEC) {
    /* ================================================================
       THE CHOOSER — which machine?

       Chris sent a screenshot of his own shop-by-collection page: a grid of
       photographs of MACHINES — a Raptor, a Maverick R, a Pro R, a sand car —
       each with the name under it and a button. "This is how I want it to look
       when somebody goes to click on Price Designs Wheels, because he has so
       many options... obviously when they click on truck, it goes to truck
       wheel pattern, and then it asks what wheel they want to build, the lug
       pattern it's in."

       An earlier version of this grouped wheel RENDERS under lane headings.
       That was the wrong first question. Someone landing on a brand with seven
       configurators knows what they drive long before they know which face
       they want, so the first screen has to be answerable at a glance — and a
       photograph of the machine is answerable at a glance in a way a beadlock
       render is not, because all seven wheels look broadly alike.

       Picking the machine also settles the fitment on six of the seven: a Pro
       R is drilled 4x156 and a Maverick R 4x137, so the pattern is a fact
       about the machine rather than a question. The truck is the exception —
       a 17x9 blank is cut to order in five patterns — so that tile says so,
       and the builder behind it pre-selects from the truck in the finder.
       ================================================================ */
    var all = Object.keys(window.BUILDERS).map(function (k) { return window.BUILDERS[k]; })
      .sort(function (a, b) { return (a.rank || 0) - (b.rank || 0); });
    var bad = q.get("b");

    root.innerHTML =
      '<section class="vizhead fade">' +
        '<p class="kicker"><b>Price Designs</b> · built to order</p>' +
        "<h1>What are you building for?</h1>" +
        '<p class="vizhead__lead">' +
          (bad ? "We couldn’t find that builder, so here’s every machine. " : "") +
          "Forged in Gilbert, Arizona and cut to your spec. Pick the machine and the " +
          "bolt pattern comes with it — then the wheel builds itself on screen as you choose." +
        "</p>" +
      "</section>" +
      '<div class="mpick fade">' +
        all.map(function (s) {
          return '<a class="mpick__c" href="build.html?b=' + esc(s.id) + '">' +
            '<span class="mpick__img">' +
              '<img src="' + esc(s.photo || s.card) + '" alt="' + esc(s.platform) + '" loading="lazy" />' +
            "</span>" +
            '<span class="mpick__t">' + esc(s.short || s.platform) + "</span>" +
            '<span class="mpick__f">' +
              (s.bolt ? esc(s.bolt) : "Cut to your pattern") +
              " · from " + money(s.basePrice) +
            "</span>" +
            '<span class="mpick__go">Build yours</span>' +
          "</a>";
        }).join("") +
      "</div>" +
      '<p class="vnote mpick__note">Set of four, Price Designs’ own prices. ' +
        "Six of these are drilled to the machine at the factory, so there is no pattern " +
        "to choose; the truck is cut to order in five, and we pre-select yours from the " +
        "truck you gave the finder. Fitment verified before we build.</p>";
    if (window.__observeFades) window.__observeFades();
    return;
  }

  /* Fitment is SOFT on purpose. wheel.js hard-requires it and a missing script
     tag silently blanks the whole page; here a missing Fitment just means we
     cannot pre-select a lug pattern, which is a lost bonus rather than a
     broken page. */
  var F = window.Fitment || null;

  /* ---- state ---------------------------------------------------------- */
  var S = {
    pick: {},       // stepId -> value. What they CLICKED, including steps not currently shown.
    text: {},
    touched: {},    // set only by a real click, so a prefill never overwrites a choice
    prefill: null,
    noFit: null,
    vehicle: null,
    showErrors: false,
    open: {}       // stepId -> true once they ask to see every finish
  };

  /* His own opening state, so the stage shows a finished wheel on arrival
     rather than a bare barrel. Not marked touched — a saved truck still wins
     on the lug step. */
  Object.keys(SPEC.defaults || {}).forEach(function (k) { S.pick[k] = SPEC.defaults[k]; });

  /* ---- visibility ----------------------------------------------------
     The rule itself lives in builder-logic.js, because the scraper, the card
     tool and the price ceiling all have to agree with it — see that file's
     header for the rule and for why it is not the obvious one. */
  var L = window.BuilderLogic;

  function visible(pick) { return L.visible(SPEC.steps, pick); }

  /* One evaluation per render, read by everything below. */
  var V = visible(S.pick);
  function refresh() { V = visible(S.pick); }

  function chosen(step) { return L.optionOf(step, V.pick[step.id]); }

  /* Steps the customer actually answers. A fact is in force but is not a
     question, and the notes box is not a choice. */
  function asked() { return V.steps.filter(function (s) { return s.type === "chips"; }); }
  function priced() { return L.priced(V); }

  function labelFor(step) {
    return String(step.label).replace(/\{(\w+)\}/g, function (_, id) {
      var st = SPEC.steps.filter(function (x) { return x.id === id; })[0];
      var o = st ? chosen(st) : null;
      return o ? o.v : "";
    }).replace(/\s+/g, " ").trim();
  }

  function total() { return L.total(SPEC, V); }

  function missing() {
    return V.steps.filter(function (st) {
      if (!st.required || st.type === "fact") return false;
      return st.type === "text" ? !String(S.text[st.id] || "").trim() : !V.pick[st.id];
    });
  }

  function configId() {
    return SPEC.id + ":" + priced().map(function (s) {
      return V.pick[s.id] ? slug(V.pick[s.id]) : "-";
    }).join(".");
  }

  function summaryLine() {
    return priced().filter(function (s) { return V.pick[s.id]; })
      .map(function (s) { return V.pick[s.id]; }).join(" · ");
  }

  /* ---- the live render ------------------------------------------------- */
  function layerUrl(file) {
    return /^https?:|^assets\//.test(file) ? file : SPEC.layerBase + file;
  }

  /* THE STAGE ALWAYS SHOWS A WHOLE WHEEL.

     The layer stack is one transparent render per answered step — barrel, face,
     ring, caps, hardware. Early on most of those steps are unanswered, and some
     are not even on the page yet (the lug pattern gates the model, the model
     gates the finish), so a stack built strictly from the live answers draws a
     ring and some hardware floating around a hole. Switching model does it too:
     the new model's finish step arrives blank, and the face disappears until
     you pick a colour. Chris: "the wheel is halfway there and the other half of
     the wheel is nonexistent."

     So the render — and ONLY the render — is completed: the customer's answers
     over the builder's own opening state, with anything still unanswered filled
     from the first no-cost option. The wheel is whole from the first paint and
     every choice made so far is on it; the parts not yet chosen show their
     default, which is what they would be.

     The PRICE, the readout, the "n of m chosen" count and the required-step
     check all keep reading `V`, the live answers. Nothing is bought here that
     was not picked — the stage is a preview, not the invoice. */
  function layerPlan() {
    var render = L.complete(SPEC, assign(assign({}, SPEC.defaults), V.pick), { gate: false });
    return L.layerPlan(SPEC, render);
  }
  function assign(a, b) { for (var k in b) if (b[k] !== undefined) a[k] = b[k]; return a; }

  /* stepId -> the <img> on screen for it, and the file it is MEANT to be
     showing. Keeping `want` separate from the element is what makes a slow
     layer safe: when it finally loads we can tell whether it is still wanted
     or whether the customer has moved on to another colour. */
  var live = {};        // key -> {el, want}
  function paintLayers() {
    var stage = document.getElementById("bStage");
    if (!stage) return;
    var plan = layerPlan(), keep = {};

    plan.forEach(function (L, i) {
      keep[L.key] = 1;
      var slot = live[L.key] || (live[L.key] = { el: null, want: null });
      if (slot.want === L.file) {
        if (slot.el) slot.el.style.zIndex = i + 1;
        return;
      }
      slot.want = L.file;

      var img = new Image();
      img.className = "wlayer";
      img.alt = "";
      img.decoding = "async";
      img.style.zIndex = i + 1;
      img.addEventListener("load", function () {
        /* Still the colour they want? A layer that arrives late after two more
           clicks must not stamp itself over the current one. */
        if (live[L.key] !== slot || slot.want !== L.file) return;
        if (slot.el && slot.el.parentNode) slot.el.parentNode.removeChild(slot.el);
        slot.el = img;
        stage.appendChild(img);
        stage.classList.add("wstage--on");
      });
      img.addEventListener("error", function () {
        /* A layer that 404s must not leave the previous colour showing as if
           it were the choice. Drop it and let the stack read honestly. */
        if (live[L.key] !== slot || slot.want !== L.file) return;
        if (slot.el && slot.el.parentNode) slot.el.parentNode.removeChild(slot.el);
        slot.el = null;
      });
      img.src = layerUrl(L.file);
    });

    /* A step that is no longer visible takes its layer with it. */
    Object.keys(live).forEach(function (k) {
      if (keep[k]) return;
      if (live[k].el && live[k].el.parentNode) live[k].el.parentNode.removeChild(live[k].el);
      delete live[k];
    });
  }

  /* ---- the fitment tie-in --------------------------------------------- */
  /* Read localStorage directly rather than calling script.js's getVeh():
     script.js loads LAST on every page and this IIFE runs at parse time, so
     getVeh is not defined yet. Three lines beats a load-order dependency that
     fails silently. */
  function readVeh() {
    try { return JSON.parse(localStorage.getItem("drooolyVehicle")); } catch (e) { return null; }
  }

  /* The truck builder asks for a lug pattern; the UTVs do not, because the
     machine is drilled at the factory. Find it by the data rather than by a
     hard-coded step id, so a renamed category cannot quietly kill the tie-in. */
  function lugStep() {
    return SPEC.steps.filter(function (s) {
      return (s.options || []).some(function (o) { return o.bolt; });
    })[0] || null;
  }

  function prefillLug() {
    var st = lugStep();
    if (!st || !F || S.touched[st.id]) return;
    var v = readVeh();
    if (!v || !v.make || !v.model) return;
    var hit = F.boltPattern({ year: v.year, make: v.make, model: v.model });
    if (!hit) return;
    S.vehicle = v;
    var o = (st.options || []).filter(function (x) { return x.bolt === hit.bolt; })[0];
    if (!o) {
      /* An honest negative. Their truck resolved, we just do not build this
         wheel in its pattern — an F-450's 10x225, a Ram 1500's 5x139.7. Say so
         rather than leaving the step mysteriously blank. */
      S.noFit = { bolt: hit.bolt, why: [v.year, v.make, v.model].join(" ") };
      return;
    }
    S.pick[st.id] = o.v;
    S.prefill = { step: st.id, why: [v.year, v.make, v.model].join(" "), bolt: hit.bolt,
                  confidence: hit.confidence, exact: hit.exact };
  }

  /* ---- rendering ------------------------------------------------------ */
  function chipsFor(step) {
    var opts = step.options || [];
    var anyPrice = opts.some(function (o) { return o.add; });

    /* A swatch GRID needs at least two pictures to be a grid. The seven
       post-cut steps are yes/no, and only the "yes" carries art — which rendered
       the "no" as an empty square that read as a broken image, and as a solid
       black void once selected. Chris, looking at it cold: "some wheels look
       like they're not clickable at all."

       So the grid needs EVERY answer to have a picture, and at least two of
       them. Anything else is words. A grid where some cells are empty is worse
       than no grid at all — the empty ones read as unavailable. */
    var withSw = opts.filter(function (o) { return o.swatch; }).length;
    var anySw = withSw === opts.length && withSw >= 2;
    /* Forty-six paint colours is a swatch grid; three ring models is a row of
       words. Same control either way — the difference is only whether a
       picture tells the customer more than the name does. */
    return '<div class="vchips' + (anySw ? " vchips--sw" : "") + '" data-step="' + esc(step.id) + '">' +
      opts.map(function (o) {
        var on = V.pick[step.id] === o.v;
        var cls = "vchip" + (anySw ? " vchip--sw" : (anyPrice ? " vchip--stack" : "")) + (on ? " on" : "");
        /* The caption is wrapped so it can fill edge-to-edge when chosen. A
           corner tick was the first attempt and it was 8px of hairline in the
           narrowest part of the tile — technically present, invisible in use.
           A filled caption bar reads at any size and leaves the paint on show,
           which is the whole point of a swatch. */
        var inner = anySw
          ? '<img src="' + esc(SPEC.layerBase + o.swatch) + '" alt="" loading="lazy" />' +
            '<span class="vchip__cap">' + esc(o.v) +
            (o.add ? "<i>+" + money(o.add) + "</i>" : "") + "</span>"
          : esc(o.v) + (o.add ? "<i>+" + money(o.add) + "</i>" : "");
        return '<button type="button" class="' + cls + '" data-v="' + esc(o.v) + '"' +
          (on ? ' aria-pressed="true"' : ' aria-pressed="false"') +
          ' title="' + esc(o.v) + (o.add ? " +" + money(o.add) : "") + '">' +
          inner + "</button>";
      }).join("") + "</div>";
  }

  function noteFor(step) {
    if (!S.prefill && !S.noFit) return "";
    var st = lugStep();
    if (!st || st.id !== step.id) return "";
    if (S.noFit) {
      return '<p class="vnote vnote--flag">Your ' + esc(S.noFit.why) + " runs " + esc(S.noFit.bolt) +
        ", and this set is not built in that pattern. " +
        '<a class="blink" href="index.html#fitment">Tell us what you’re building</a> ' +
        "and we’ll find the wheel that is.</p>";
    }
    var soft = S.prefill.confidence === "check" || !S.prefill.exact;
    return '<p class="vnote' + (soft ? " vnote--flag" : "") + '">Pre-selected from your ' +
      esc(S.prefill.why) + " — " + esc(S.prefill.bolt) + ". Change it if that’s not the truck. " +
      (soft ? "We’ll confirm this pattern with you before anything is cut."
            : "Fitment verified before we build.") + "</p>";
  }

  function renderSteps() {
    var host = document.getElementById("bSteps");
    var missIds = S.showErrors ? missing().map(function (s) { return s.id; }) : [];
    host.innerHTML = V.steps.map(function (st) {
      if (st.type === "text") return '<div class="vfld" data-step="' + esc(st.id) + '" data-text="1"></div>';
      if (st.type === "fact") {
        return '<div class="vfld vfld--fact" data-step="' + esc(st.id) + '">' +
          "<label>" + esc(labelFor(st)) + "<b>" + esc(st.options[0].v) + "</b></label>" +
          '<p class="vnote">The only one built for this platform.</p></div>';
      }
      var o = chosen(st);
      var bad = missIds.indexOf(st.id) > -1;
      return '<div class="vfld' + (bad ? " vfld--hero" : "") + '" data-step="' + esc(st.id) + '">' +
        "<label>" + esc(labelFor(st)) + "<b>" + (o ? esc(o.v) : "—") + "</b></label>" +
        chipsFor(st) +
        (bad ? '<p class="vnote vnote--flag">Pick one to finish your build.</p>' : noteFor(st)) +
        "</div>";
    }).join("");
    mountText();
    clipGroups();
  }

  /* Forty-six paint tiles per finish step, across five or six finish steps, is
     a page nobody scrolls — Pro R alone opens with three of them. So the long
     grids start collapsed.

     Collapsing is safe here only because the step's own label already carries
     the current answer on the right ("FACE FINISH … Illusion blueberry"), so
     the choice is readable whether or not its tile is above the fold. Without
     that it would be the wrong trade and the grid would have to stay open.

     A group opens for good once they ask for it, OR once they pick from it —
     someone choosing a colour is browsing colours, and snapping the grid shut
     under them on every click would be unusable. */
  function clipGroups() {
    [].forEach.call(document.querySelectorAll(".vchips--sw"), function (grid) {
      var step = grid.dataset.step;
      var chips = grid.children.length;
      if (S.open[step] || chips <= 12) return;

      grid.classList.add("is-clipped");
      var more = document.createElement("button");
      more.type = "button";
      more.className = "vmore";
      more.dataset.step = step;
      more.textContent = "Show all " + chips + " finishes";
      grid.parentNode.insertBefore(more, grid.nextSibling);
    });
  }

  /* The textarea is built once and never re-rendered — a rebuild mid-sentence
     would drop the caret. renderSteps() leaves an empty shell for it. */
  var textEl = null;
  function mountText() {
    var st = SPEC.steps.filter(function (s) { return s.type === "text"; })[0];
    if (!st) return;
    var shell = document.querySelector('.vfld[data-step="' + st.id + '"][data-text="1"]');
    if (!shell) return;
    if (!textEl) {
      textEl = document.createElement("textarea");
      textEl.id = "bNotes";
      textEl.rows = 3;
      textEl.placeholder = st.placeholder || "";
      textEl.addEventListener("input", function () { S.text[st.id] = textEl.value; });
    }
    shell.innerHTML = "<label>" + esc(labelFor(st)) + "<b>optional</b></label>";
    shell.appendChild(textEl);
  }

  function renderStage() {
    var t = total();
    var ask = asked();
    var done = ask.filter(function (s) { return V.pick[s.id]; }).length;
    document.getElementById("bTotal").innerHTML =
      "<span>Set of " + SPEC.setOf + " · " + done + " of " + ask.length + " chosen</span>" +
      "<b>" + money(t) + "</b>";
    document.getElementById("bPer").textContent = money(Math.round(t / SPEC.setOf)) + " per wheel";

    /* One option in his whole catalogue has no render (CAN-AM YELLOW on the
       Psycho face). Rather than show a wheel with a hole in it and let the
       customer conclude the page is broken, say which part cannot be previewed
       — the wheel is still built to it. */
    var unrendered = priced().filter(function (s) {
      var o = chosen(s); return o && o.noRender;
    });
    var warn = document.getElementById("bNoRender");
    if (warn) {
      warn.hidden = !unrendered.length;
      warn.innerHTML = unrendered.length
        ? "The preview can’t show " + unrendered.map(function (s) {
            return "<b>" + esc(chosen(s).v) + "</b> on the " +
                   esc(labelFor(s).toLowerCase().replace(/\?$/, ""));
          }).join(" or ") + " — Price Designs builds it, we just don’t hold a " +
          "render of it yet. Everything else on the wheel is shown."
        : "";
    }

    document.getElementById("bReadout").innerHTML = priced().map(function (s) {
      var o = chosen(s);
      return '<div class="vstat"><span>' + esc(labelFor(s)) + "</span><b>" +
        (o ? esc(o.v) + (o.add ? " · +" + money(o.add) : "") : "—") + "</b></div>";
    }).join("");
    paintLayers();
  }

  /* On a phone the stage scrolls away above twenty steps, taking the running
     total with it. A fixed bar keeps the number and the action in reach —
     desktop hides it, because there the stage is sticky already. */
  var bbar = null;
  function renderBar() {
    if (!bbar) {
      bbar = document.createElement("div");
      bbar.className = "bbar";
      bbar.innerHTML = '<div class="bbar__v"><span></span><b></b></div>' +
        '<button class="btn btn--primary btn--sm" type="button"><span class="btn-txt">Send build</span></button>';
      bbar.querySelector("button").addEventListener("click", function () {
        document.getElementById("bSubmit").click();
      });
      document.body.appendChild(bbar);
      document.body.classList.add("has-bbar");
    }
    var ask = asked();
    var done = ask.filter(function (s) { return V.pick[s.id]; }).length;
    bbar.querySelector("span").textContent = "Set of " + SPEC.setOf + " · " + done + "/" + ask.length;
    bbar.querySelector("b").textContent = money(total());
  }

  function render() { refresh(); renderSteps(); renderStage(); renderBar(); }

  function serialise() {
    return {
      v: 2,
      builderId: SPEC.id,
      brand: SPEC.brandName,
      brandSlug: SPEC.brand,
      platform: SPEC.platform,
      title: SPEC.title + " — " + SPEC.subtitle.toLowerCase(),
      setOf: SPEC.setOf,
      basePrice: SPEC.basePrice,
      total: total(),
      perWheel: Math.round(total() / SPEC.setOf),
      currency: "USD",
      img: SPEC.image,
      configId: configId(),
      choices: priced().filter(function (s) { return V.pick[s.id]; }).map(function (s) {
        var o = chosen(s);
        return { stepId: s.id, step: labelFor(s), value: o.v, add: o.add || 0 };
      }),
      /* The exact stack that was on screen, so the shop can rebuild the picture
         the customer approved rather than infer it from the words. */
      layers: layerPlan().map(function (L) { return layerUrl(L.file); }),
      notes: String(S.text.notes || "").trim(),
      summary: summaryLine(),
      vehicle: S.vehicle || null,
      boltPattern: (function () {
        var st = lugStep();
        if (st) { var o = chosen(st); return o ? o.bolt : null; }
        return SPEC.bolt || null;
      })(),
      lugSource: S.prefill ? "finder" : (lugStep() ? "customer" : "platform"),
      builtAt: new Date().toISOString()
    };
  }

  /* ---- actions -------------------------------------------------------- */
  function pick(stepId, v) {
    S.pick[stepId] = v;
    S.touched[stepId] = true;
    /* Picking inside a collapsed grid means they are shopping that grid — it
       stays open. See clipGroups(). */
    S.open[stepId] = true;
    var st = lugStep();
    if (st && st.id === stepId) { S.prefill = null; S.noFit = null; }
    refresh();
    if (S.showErrors && !missing().length) S.showErrors = false;
    render();
  }

  function reset() {
    S.pick = {}; S.text = {}; S.touched = {}; S.prefill = null; S.noFit = null;
    S.showErrors = false; S.open = {};
    Object.keys(SPEC.defaults || {}).forEach(function (k) { S.pick[k] = SPEC.defaults[k]; });
    if (textEl) textEl.value = "";
    prefillLug();                 // back to what we know, not to blank
    render();
  }

  /* ---- page ----------------------------------------------------------- */
  root.innerHTML =
    '<section class="vizhead fade">' +
      '<p class="kicker"><b>' + esc(SPEC.brandName) + "</b> · " + esc(SPEC.platform) + "</p>" +
      "<h1>" + esc(SPEC.title) + "</h1>" +
      '<p class="vizhead__lead">' + esc(SPEC.subtitle) + ". " + esc(SPEC.madeIn) + "</p>" +
      '<p class="vizhead__note">' + esc(SPEC.includes) +
        (SPEC.bolt ? " Drilled " + esc(SPEC.bolt) + " to suit the platform." : "") + "</p>" +
      '<p class="vizhead__back"><a class="blink" href="build.html">← Every Price Designs builder</a></p>' +
    "</section>" +
    '<div class="vizgrid vizgrid--build">' +
      '<section class="vizpanel" id="bSteps"></section>' +
      '<aside class="vizstage fade">' +
        '<div class="wstage" id="bStage" style="aspect-ratio:' +
          ((SPEC.stage && SPEC.stage.w) || 1) + "/" + ((SPEC.stage && SPEC.stage.h) || 1) + '">' +
          '<img class="wstage__fb" src="' + esc(SPEC.card || SPEC.image) + '" alt="' +
            esc(SPEC.brandName + " " + SPEC.title) + '" />' +
        "</div>" +
        '<p class="vnote vnote--flag bnorender" id="bNoRender" hidden></p>' +
        '<div class="vfld--hero bprice" id="bTotal"></div>' +
        '<p class="vnote" id="bPer"></p>' +
        '<div class="vreadout" id="bReadout"></div>' +
        '<div class="vcta">' +
          '<button class="btn btn--primary" id="bSubmit"><span class="btn-txt">Send this build to DROOOLY</span></button>' +
          '<button class="vpin" id="bReset">Start over</button>' +
        "</div>" +
        '<p class="vnote">Prices are ' + esc(SPEC.brandName) + "’s own, for the set, and so is the " +
          "render — it shows the combination you picked. Finishes vary a little between a screen " +
          "and a cut wheel.</p>" +
      "</aside>" +
    "</div>";

  /* one delegated listener, so re-rendering the chips never leaks handlers */
  document.getElementById("bSteps").addEventListener("click", function (e) {
    var more = e.target.closest(".vmore");
    if (more) { S.open[more.dataset.step] = true; render(); return; }
    var chip = e.target.closest(".vchip");
    if (!chip) return;
    pick(chip.closest(".vchips").dataset.step, chip.dataset.v);
  });

  document.getElementById("bReset").addEventListener("click", reset);

  document.getElementById("bSubmit").addEventListener("click", function () {
    var miss = missing();
    if (miss.length) {
      S.showErrors = true; render();
      var el = document.querySelector('.vfld[data-step="' + miss[0].id + '"]');
      if (el) el.scrollIntoView({ block: "center", behavior: "smooth" });
      return;
    }
    var build = serialise();
    try { localStorage.setItem("drooolyBuild", JSON.stringify(build)); } catch (e) {}

    /* ---- CART SEAM ---------------------------------------------------
       Deferred deliberately — Chris: "the payment side of it, or how you
       can add it to your cart, let's do that at the very end." This is the
       ONLY call site, so that decision is one edit.

       Three things have to change in cart.js first, and none of them are
       cosmetic:
         1. cart.js:18 — the stored literal is exactly
            {key, brand, name, price, img, qty}. It DROPS unknown fields, so
            `choices`, `layers` and `notes` would vanish on the way in.
         2. cart.js render() concatenates brand/name into innerHTML with no
            escaping. Nothing user-controlled reaches it today; a build
            carrying a free-text note would be the first, and that is an XSS
            hole. Escape it before wiring this up.
         3. `key` is the dedupe identity. configId is already the right one —
            two different builds of the same wheel must not merge into a
            single line with qty 2.

       window.Cart.add({ key: build.configId, brand: build.brand,
                         name: build.title, price: build.total,
                         img: build.img, qty: 1, build: build });
    -------------------------------------------------------------------- */

    location.href = "index.html?w=" + encodeURIComponent(build.brand + " " + build.title +
      " — " + build.summary + " (" + money(build.total) + ")") + "#fitment";
  });

  /* public surface, so whoever closes the cart seam has one thing to call */
  window.Builder = {
    get: serialise, summary: summaryLine, reset: reset, total: total,
    visible: function () { return V.steps.map(function (s) { return s.id; }); },
    layers: layerPlan
  };

  /* ON A PHONE THE WHEEL HAS TO BE ABOVE THE QUESTIONS.

     The grid is one column at this width and .vizstage comes second in the
     DOM, so the render ended up 6,545px down the page — below all twelve
     steps. A customer configured the entire wheel without ever seeing it
     change, which is the one thing this page exists to do.

     Only the RENDER moves. The rest of .vizstage — the running total, the
     build readout, the CTA — is a summary and belongs after the questions,
     so moving the whole aside would put the summary before the thing it
     summarises. The element is moved rather than duplicated: two copies
     would mean paintLayers() keeping two stacks of nine images in step.

     Reversible, because the layout flips back above 820px. */
  function placeStage() {
    var grid = document.querySelector(".vizgrid--build");
    var stage = document.getElementById("bStage");
    var aside = document.querySelector(".vizstage");
    if (!grid || !stage || !aside) return;
    var phone = window.matchMedia("(max-width: 819px)").matches;
    if (phone && stage.parentNode !== grid) {
      grid.insertBefore(stage, grid.firstChild);
      stage.classList.add("wstage--lead");
    } else if (!phone && stage.parentNode === grid) {
      aside.insertBefore(stage, aside.firstChild);
      stage.classList.remove("wstage--lead");
    }
  }

  prefillLug();
  render();
  placeStage();
  window.addEventListener("resize", placeStage);
  if (window.__observeFades) window.__observeFades();
})();
