/* GENERATED by tools/build-specs.js — do not edit.
   Source of truth: data/specs/*.json
   Rebuild: node tools/build-specs.js
   5 JTX dually models · art verified present at build time. */
window.WHEEL_SPECS = {
  "wheels": {
    "jtx": {
      "brand": "JTX Forged",
      "brandSlug": "jtx",
      "program": "Dually Series",
      "captured": "2026-08-27",
      "sources": [
        "https://jtxforged.com/dually-series/",
        "https://jtxforged.com/combat-dually/",
        "https://jtxforged.com/centerfire-dually/",
        "https://jtxforged.com/capo-dually/",
        "https://jtxforged.com/silencer-dually/",
        "https://jtxforged.com/flight-dually/"
      ],
      "offsetPublished": false,
      "rearWidth": 8.25,
      "diameters": [
        22,
        24,
        26,
        28,
        30
      ],
      "front": {
        "standard": {
          "22": [
            8.25
          ],
          "24": [
            8.25
          ],
          "26": [
            8.25
          ],
          "28": [
            8.25
          ],
          "30": [
            8.25
          ]
        },
        "superSingle": {
          "22": [
            10,
            12,
            14
          ],
          "24": [
            10,
            12,
            14
          ],
          "26": [
            10,
            12,
            14,
            16
          ],
          "28": [
            14,
            16
          ],
          "30": [
            16
          ]
        }
      },
      "finishes": [
        {
          "code": "polished",
          "name": "Polished",
          "rendered": true
        },
        {
          "code": "black",
          "name": "Black Milled",
          "rendered": true
        },
        {
          "code": "brushed",
          "name": "Brushed",
          "rendered": false
        },
        {
          "code": "custom",
          "name": "Custom",
          "rendered": false
        }
      ],
      "artPattern": "assets/wheels/jtx/drw/{model}-{position}-{finish}.webp",
      "artSource": "https://jtxforged.com/wp-content/uploads/2023/12/",
      "models": [
        {
          "slug": "combat",
          "name": "Combat",
          "url": "https://jtxforged.com/combat-dually/"
        },
        {
          "slug": "centerfire",
          "name": "Centerfire",
          "url": "https://jtxforged.com/centerfire-dually/"
        },
        {
          "slug": "capo",
          "name": "Capo",
          "url": "https://jtxforged.com/capo-dually/"
        },
        {
          "slug": "silencer",
          "name": "Silencer",
          "url": "https://jtxforged.com/silencer-dually/"
        },
        {
          "slug": "flight",
          "name": "Flight",
          "url": "https://jtxforged.com/flight-dually/"
        }
      ]
    }
  },
  "vehicles": {
    "f450": {
      "id": "f450",
      "name": "Ford F-450 Super Duty",
      "detail": "2017–2022 pickup, dual rear wheel",
      "config": "drw",
      "captured": "2026-08-27",
      "sources": [
        "https://www.wheel-size.com/size/ford/f-450-super-duty/2020/",
        "https://www.wheel-size.com/pcd/10x225/ford/f-450-super-duty/2017-2022/"
      ],
      "bolt": "10x225",
      "hubBoreMm": 170.1,
      "oem": {
        "wheel": "19.5x6",
        "offsetMm": 136,
        "tire": "LT225/70R19.5"
      },
      "rear": {
        "offsetMm": {
          "min": 110,
          "max": 130,
          "typical": 120
        },
        "backspacingIn": {
          "min": 6.5,
          "max": 7
        }
      },
      "frontSuperSingle": {
        "offsetMm": null,
        "source": null
      },
      "measured": false
    }
  }
};
