#!/usr/bin/env node
/* Generates wheel-specs.js from data/specs/*.json.
   node tools/build-specs.js

   CLAUDE.md: "Product data must be file- or CMS-driven, never hardcoded in
   components." The JSON under data/specs is the record — hand-edit that, never
   the generated file. It carries its own sources and capture date so the next
   person can tell what was verified and when.

   This is deliberately separate from brands.js: build-featured.js round-trips
   that file through a field whitelist and would silently drop anything added
   here.                                                                      */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SPECS = path.join(ROOT, "data", "specs");
const OUT = path.join(ROOT, "wheel-specs.js");

function read(name) {
  return JSON.parse(fs.readFileSync(path.join(SPECS, name), "utf8"));
}

// Strip underscore-prefixed keys — they document the data for humans editing
// the JSON and have no business being shipped to a browser.
function strip(v) {
  if (Array.isArray(v)) return v.map(strip);
  if (v && typeof v === "object") {
    const out = {};
    for (const k of Object.keys(v)) if (!k.startsWith("_")) out[k] = strip(v[k]);
    return out;
  }
  return v;
}

const jtx = read("jtx-dually.json");
const f450 = read("f450-fitment.json");
const offsets = read("offsets.json");
const jtxSizes = read("jtx-sizes.json");

/* A number without a source is a number somebody made up. This is the gate
   that stops the next person pasting in a plausible ET — same treatment the
   plate and art checks get below. */
Object.keys(offsets.roles).forEach(function (role) {
  var r = offsets.roles[role];
  [["widths", r.widths], ["bySize", r.bySize]].forEach(function (pair) {
    var bucket = pair[1] || {};
    Object.keys(bucket).forEach(function (key) {
      var e = bucket[key];
      var stated = ["typical", "min", "max"].some(function (k) { return typeof e[k] === "number"; });
      if (stated && !e.source) {
        console.error("ERROR: offsets." + role + "." + pair[0] + "." + key +
          " states a figure with no source.");
        process.exit(1);
      }
    });
  });
});

/* jtx-sizes.json is GENERATED by tools/scrape-jtx-sizes.js, so the thing worth
   checking is not "did someone cite a source" but "is this still a record of a
   real scrape". A hand-edited copy with the provenance torn off is exactly the
   invented data this whole exercise removed. */
(function lintSizes() {
  const need = ["generator", "captured", "sources", "pagesScraped", "verifiedPages"];
  const missing = need.filter((k) => !jtxSizes[k]);
  if (missing.length) {
    console.error("ERROR: jtx-sizes.json has no " + missing.join(", ") +
      " — it must come from tools/scrape-jtx-sizes.js, not by hand.");
    process.exit(1);
  }
  // Every list must actually list something. An empty role would render as a
  // wheel that comes in no sizes at all.
  const buckets = [["roles", jtxSizes.roles]];
  Object.keys(jtxSizes.models || {}).forEach((m) => buckets.push(["models." + m, jtxSizes.models[m]]));
  buckets.forEach(function (pair) {
    Object.keys(pair[1] || {}).forEach(function (role) {
      const dias = Object.keys(pair[1][role] || {});
      if (!dias.length || dias.some((d) => !pair[1][role][d].length)) {
        console.error("ERROR: jtx-sizes." + pair[0] + "." + role + " has an empty size list.");
        process.exit(1);
      }
    });
  });
  if (!jtxSizes.roles.single && !Object.keys(jtxSizes.models || {}).length) {
    console.error("ERROR: jtx-sizes.json carries no sizes at all.");
    process.exit(1);
  }
})();

/* Photo plates: a base truck photo plus where its wheels sit, so the preview
   can composite a real render into a real photograph. Kept as data because the
   plate is the thing most likely to be replaced — a new photo is a new JSON
   and one calibration pass, not a code change. */
const PLATES = path.join(ROOT, "data", "plates");
const plates = fs.existsSync(PLATES)
  ? fs.readdirSync(PLATES).filter(function (f) { return f.endsWith(".json"); })
      .map(function (f) { return JSON.parse(fs.readFileSync(path.join(PLATES, f), "utf8")); })
  : [];

plates.forEach(function (pl) {
  if (!fs.existsSync(path.join(ROOT, pl.image))) {
    console.error("ERROR: plate " + pl.id + " names a missing image: " + pl.image);
    process.exit(1);
  }
  // A plate with no usable wheel can't render anything — catch it here rather
  // than shipping a page that silently shows a bare photo.
  if (!pl.wheels.some(function (w) { return w.usable; })) {
    console.error("ERROR: plate " + pl.id + " has no usable wheel anchor.");
    process.exit(1);
  }
});

/* Every art file the spec claims must actually exist, or the visualizer
   renders a broken image. Fail the build instead. */
const missing = [];
for (const m of jtx.models) {
  for (const f of jtx.finishes.filter((x) => x.rendered)) {
    for (const pos of ["front", "rear", "supersingle"]) {
      const rel = jtx.artPattern
        .replace("{model}", m.slug)
        .replace("{position}", pos)
        .replace("{finish}", f.code);
      if (!fs.existsSync(path.join(ROOT, rel))) missing.push(rel);
    }
  }
}
if (missing.length) {
  console.error(`ERROR: ${missing.length} art file(s) named by the spec are missing:`);
  missing.slice(0, 10).forEach((m) => console.error("  " + m));
  process.exit(1);
}

/* The JSON keeps the full audit trail (which pages were scraped, which lists
   varied and on what models); the browser needs none of it. Ship the lookup
   tables only — 50 KB of provenance does not belong in a page load. */
const shippedSizes = {
  captured: jtxSizes.captured,
  roles: strip(jtxSizes.roles),
  models: strip(jtxSizes.models),
  rearWidth: jtxSizes.rearWidth,
  customSizes: jtxSizes.customSizes ? { quote: jtxSizes.customSizes.quote } : null,
  customProfile: jtxSizes.customProfile ? { quote: jtxSizes.customProfile.quote } : null,
};

const payload = {
  wheels: { jtx: Object.assign(strip(jtx), { sizes: shippedSizes }) },
  vehicles: { f450: strip(f450) },
  plates: strip(plates),
  offsets: strip(offsets)
};

const banner = `/* GENERATED by tools/build-specs.js — do not edit.
   Source of truth: data/specs/*.json
   Rebuild: node tools/build-specs.js
   ${jtx.models.length} JTX dually models, ${plates.length} photo plate(s).
   Art and plate images verified present at build time. */
`;

/* Indented JSON puts every width on its own line, which turned a lookup table
   of ~700 numbers into 60 KB of whitespace. Keep the indentation that makes the
   file readable in a diff, but let short numeric arrays sit on one line. */
function compactNumberArrays(json) {
  return json.replace(/\[\s*\n\s*(-?[\d.]+(?:,\s*\n\s*-?[\d.]+)*)\s*\n\s*\]/g,
    function (_, body) { return "[" + body.split(/,\s*\n\s*/).join(", ") + "]"; });
}

fs.writeFileSync(
  OUT,
  banner + "window.WHEEL_SPECS = " +
    compactNumberArrays(JSON.stringify(payload, null, 2)) + ";\n"
);

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
var sourced = 0, gaps = [];
Object.keys(offsets.roles).forEach(function (role) {
  var w = offsets.roles[role].widths || {};
  Object.keys(w).forEach(function (k) {
    if (typeof w[k].typical === "number" || typeof w[k].min === "number") sourced++;
    else gaps.push(role + " " + k + '"');
  });
});
console.log(`  offsets: ${sourced} sourced figure(s)` +
  (gaps.length ? `, ${gaps.length} explicit gap(s): ${gaps.join(", ")}` : ""));

var lineWide = Object.keys(jtxSizes.roles || {});
var perModel = Object.keys(jtxSizes.models || {});
console.log("  jtx sizes: " + (lineWide.length ? lineWide.join("/") + " line-wide" : "none line-wide") +
  (perModel.length ? ", " + perModel.length + " models with their own lists" : "") +
  " (scraped " + jtxSizes.pagesScraped.single + " single + " + jtxSizes.pagesScraped.dually + " dually pages)");

const unclearedPlates = plates.filter(function (p) { return !p.cleared; }).map(function (p) { return p.id; });
console.log(`wheel-specs.js written — ${jtx.models.length} models, ${plates.length} plate(s), ${kb} KB, all art present`);
if (unclearedPlates.length) {
  console.log(`  NOTE: ${unclearedPlates.length} plate(s) not rights-cleared: ${unclearedPlates.join(", ")}`);
  console.log("        The page labels these as placeholders. Clear or replace before launch.");
}
