#!/usr/bin/env node
/* Generates wheel-specs.js from data/specs/*.json.
   node tools/build-specs.js

   CLAUDE.md: "Product data must be file- or CMS-driven, never hardcoded in
   components." The JSON under data/specs is the record — hand-edit that, never
   the generated file. It carries its own sources and capture date so the next
   person can tell what was verified and when.

   This is deliberately separate from brands.js: build-featured.js round-trips
   that file through a field whitelist and would silently drop anything added
   here.                                                                      */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SPECS = path.join(ROOT, "data", "specs");
const OUT = path.join(ROOT, "wheel-specs.js");

function read(name) {
  return JSON.parse(fs.readFileSync(path.join(SPECS, name), "utf8"));
}

// Strip the _note_* keys — they document the data for humans editing the JSON
// and have no business being shipped to a browser.
function strip(v) {
  if (Array.isArray(v)) return v.map(strip);
  if (v && typeof v === "object") {
    const out = {};
    for (const k of Object.keys(v)) if (!k.startsWith("_note")) out[k] = strip(v[k]);
    return out;
  }
  return v;
}

const jtx = read("jtx-dually.json");
const f450 = read("f450-fitment.json");

/* Every art file the spec claims must actually exist, or the visualizer
   renders a broken image. Fail the build instead. */
const missing = [];
for (const m of jtx.models) {
  for (const f of jtx.finishes.filter((x) => x.rendered)) {
    for (const pos of ["front", "rear", "supersingle"]) {
      const rel = jtx.artPattern
        .replace("{model}", m.slug)
        .replace("{position}", pos)
        .replace("{finish}", f.code);
      if (!fs.existsSync(path.join(ROOT, rel))) missing.push(rel);
    }
  }
}
if (missing.length) {
  console.error(`ERROR: ${missing.length} art file(s) named by the spec are missing:`);
  missing.slice(0, 10).forEach((m) => console.error("  " + m));
  process.exit(1);
}

const payload = {
  wheels: { jtx: strip(jtx) },
  vehicles: { f450: strip(f450) }
};

const banner = `/* GENERATED by tools/build-specs.js — do not edit.
   Source of truth: data/specs/*.json
   Rebuild: node tools/build-specs.js
   ${jtx.models.length} JTX dually models · art verified present at build time. */
`;

fs.writeFileSync(
  OUT,
  banner + "window.WHEEL_SPECS = " + JSON.stringify(payload, null, 2) + ";\n"
);

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`wheel-specs.js written — ${jtx.models.length} models, ${kb} KB, all art present`);
