#!/usr/bin/env node
/* build-dealer.js — ship the prune record to the browser.
 *
 * The dealer sheet derives everything else it says from brands.js at runtime,
 * on purpose: a figure that is counted cannot go stale the way the hero's
 * "780+ models" did. The one thing it cannot count from the live catalogue is
 * what is NO LONGER in it — the 93 models the discontinued-model prune took
 * out. That list is the most useful thing on the sheet for a brand rep ("if
 * any of these are current, tell us and they go back"), so it has to ship.
 *
 * The site is static and opens from file://, so it cannot fetch() JSON. Same
 * author-JSON -> generated-JS pattern as brands.js and fitment-data.js.
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const src = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'data/removed-discontinued.json'), 'utf8'));

const byBrand = {};
(src.brands || []).forEach(b => {
  byBrand[b.brand] = { n: b.n, models: b.models.slice().sort() };
});

const out =
  '/* GENERATED by tools/build-dealer.js — do not edit.\n' +
  '   Source: data/removed-discontinued.json\n' +
  '   What came out of the catalogue on ' + src.when + ', and why. */\n' +
  'window.DEALER_PRUNED = ' + JSON.stringify({
    when: src.when, why: src.why, byBrand: byBrand
  }, null, 1) + ';\n';

fs.writeFileSync(path.join(ROOT, 'dealer-data.js'), out);

const total = Object.keys(byBrand).reduce((a, k) => a + byBrand[k].n, 0);
console.log('dealer-data.js — ' + total + ' pruned models across ' +
  Object.keys(byBrand).length + ' brand(s), removed ' + src.when);
