#!/usr/bin/env node
/* Generates wheel-specs.js from data/specs/*.json.
   node tools/build-specs.js

   CLAUDE.md: "Product data must be file- or CMS-driven, never hardcoded in
   components." The JSON under data/specs is the record — hand-edit that, never
   the generated file. It carries its own sources and capture date so the next
   person can tell what was verified and when.

   This is deliberately separate from brands.js: build-featured.js round-trips
   that file through a field whitelist and would silently drop anything added
   here.                                                                      */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SPECS = path.join(ROOT, "data", "specs");
const OUT = path.join(ROOT, "wheel-specs.js");

function read(name) {
  return JSON.parse(fs.readFileSync(path.join(SPECS, name), "utf8"));
}

// Strip the _note_* keys — they document the data for humans editing the JSON
// and have no business being shipped to a browser.
function strip(v) {
  if (Array.isArray(v)) return v.map(strip);
  if (v && typeof v === "object") {
    const out = {};
    for (const k of Object.keys(v)) if (!k.startsWith("_note")) out[k] = strip(v[k]);
    return out;
  }
  return v;
}

const jtx = read("jtx-dually.json");
const f450 = read("f450-fitment.json");
const offsets = read("offsets.json");

/* A number without a source is a number somebody made up. This is the gate
   that stops the next person pasting in a plausible ET — same treatment the
   plate and art checks get below. */
Object.keys(offsets.roles).forEach(function (role) {
  var r = offsets.roles[role];
  [["widths", r.widths], ["bySize", r.bySize]].forEach(function (pair) {
    var bucket = pair[1] || {};
    Object.keys(bucket).forEach(function (key) {
      var e = bucket[key];
      var stated = ["typical", "min", "max"].some(function (k) { return typeof e[k] === "number"; });
      if (stated && !e.source) {
        console.error("ERROR: offsets." + role + "." + pair[0] + "." + key +
          " states a figure with no source.");
        process.exit(1);
      }
    });
  });
});

/* Photo plates: a base truck photo plus where its wheels sit, so the preview
   can composite a real render into a real photograph. Kept as data because the
   plate is the thing most likely to be replaced — a new photo is a new JSON
   and one calibration pass, not a code change. */
const PLATES = path.join(ROOT, "data", "plates");
const plates = fs.existsSync(PLATES)
  ? fs.readdirSync(PLATES).filter(function (f) { return f.endsWith(".json"); })
      .map(function (f) { return JSON.parse(fs.readFileSync(path.join(PLATES, f), "utf8")); })
  : [];

plates.forEach(function (pl) {
  if (!fs.existsSync(path.join(ROOT, pl.image))) {
    console.error("ERROR: plate " + pl.id + " names a missing image: " + pl.image);
    process.exit(1);
  }
  // A plate with no usable wheel can't render anything — catch it here rather
  // than shipping a page that silently shows a bare photo.
  if (!pl.wheels.some(function (w) { return w.usable; })) {
    console.error("ERROR: plate " + pl.id + " has no usable wheel anchor.");
    process.exit(1);
  }
});

/* Every art file the spec claims must actually exist, or the visualizer
   renders a broken image. Fail the build instead. */
const missing = [];
for (const m of jtx.models) {
  for (const f of jtx.finishes.filter((x) => x.rendered)) {
    for (const pos of ["front", "rear", "supersingle"]) {
      const rel = jtx.artPattern
        .replace("{model}", m.slug)
        .replace("{position}", pos)
        .replace("{finish}", f.code);
      if (!fs.existsSync(path.join(ROOT, rel))) missing.push(rel);
    }
  }
}
if (missing.length) {
  console.error(`ERROR: ${missing.length} art file(s) named by the spec are missing:`);
  missing.slice(0, 10).forEach((m) => console.error("  " + m));
  process.exit(1);
}

const payload = {
  wheels: { jtx: strip(jtx) },
  vehicles: { f450: strip(f450) },
  plates: strip(plates),
  offsets: strip(offsets)
};

const banner = `/* GENERATED by tools/build-specs.js — do not edit.
   Source of truth: data/specs/*.json
   Rebuild: node tools/build-specs.js
   ${jtx.models.length} JTX dually models, ${plates.length} photo plate(s).
   Art and plate images verified present at build time. */
`;

fs.writeFileSync(
  OUT,
  banner + "window.WHEEL_SPECS = " + JSON.stringify(payload, null, 2) + ";\n"
);

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
var sourced = 0, gaps = [];
Object.keys(offsets.roles).forEach(function (role) {
  var w = offsets.roles[role].widths || {};
  Object.keys(w).forEach(function (k) {
    if (typeof w[k].typical === "number" || typeof w[k].min === "number") sourced++;
    else gaps.push(role + " " + k + '"');
  });
});
console.log(`  offsets: ${sourced} sourced figure(s)` +
  (gaps.length ? `, ${gaps.length} explicit gap(s): ${gaps.join(", ")}` : ""));

const unclearedPlates = plates.filter(function (p) { return !p.cleared; }).map(function (p) { return p.id; });
console.log(`wheel-specs.js written — ${jtx.models.length} models, ${plates.length} plate(s), ${kb} KB, all art present`);
if (unclearedPlates.length) {
  console.log(`  NOTE: ${unclearedPlates.length} plate(s) not rights-cleared: ${unclearedPlates.join(", ")}`);
  console.log("        The page labels these as placeholders. Clear or replace before launch.");
}
