#!/usr/bin/env node
'use strict';
/*
  build-bolts.js — compile data/fitment/vehicle-bolt-patterns.json into
  vehicle-bolts.js for the browser.

  The site is static and may be opened from disk, so the browser cannot
  fetch() a JSON file. Same arrangement brands.js and builds-data.js already
  use: author the data as JSON, ship a generated .js that assigns to window.

  It also validates, because a typo in this file sends someone the wrong
  wheels. It refuses to write if:
    - a bolt string is not <count>x<pcd>
    - a year range is backwards or ends before 1990
    - two entries for the same make+model overlap in years (that is the
      Ram 1500 / 1500 Classic trap, and the resolver would silently pick one)
*/
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'data/fitment/vehicle-bolt-patterns.json');
const OUT = path.join(ROOT, 'vehicle-bolts.js');

const src = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const rows = src.patterns || [];
const errs = [];

const BOLT = /^(\d{1,2})x(\d{2,3}(?:\.\d+)?)$/;
rows.forEach((r, i) => {
  const where = `${r.make} ${r.model} ${r.from}-${r.to}`;
  if (!BOLT.test(r.bolt)) errs.push(`${where}: "${r.bolt}" is not a bolt pattern`);
  if (!(r.from >= 1990 && r.to >= r.from && r.to <= 2030)) errs.push(`${where}: year range makes no sense`);
  if (!r.make || !r.model) errs.push(`row ${i}: missing make or model`);
  if (r.confidence !== 'high' && r.confidence !== 'check') errs.push(`${where}: confidence must be high or check`);
});

// overlapping year ranges for one make+model
const byKey = new Map();
rows.forEach(r => {
  const k = `${r.make.toLowerCase()}|${r.model.toLowerCase()}`;
  (byKey.get(k) || byKey.set(k, []).get(k)).push(r);
});
for (const [k, list] of byKey) {
  list.sort((a, b) => a.from - b.from);
  for (let i = 1; i < list.length; i++) {
    if (list[i].from <= list[i - 1].to) {
      errs.push(`${k}: ${list[i - 1].from}-${list[i - 1].to} overlaps ${list[i].from}-${list[i].to} — ` +
                `the resolver cannot tell which pattern a shared year means`);
    }
  }
}

if (errs.length) {
  console.error('build-bolts: refusing to write.\n');
  errs.forEach(e => console.error('  ' + e));
  process.exit(1);
}

const payload = { version: src.version, built: src.built, makeAliases: src.makeAliases || {}, patterns: rows };
fs.writeFileSync(OUT,
  '/* GENERATED by tools/build-bolts.js from data/fitment/vehicle-bolt-patterns.json.\n' +
  '   Do not edit — edit the JSON and re-run the tool. */\n' +
  'window.VEHICLE_BOLTS = ' + JSON.stringify(payload) + ';\n');

const makes = new Set(rows.map(r => r.make));
const bolts = new Map();
rows.forEach(r => bolts.set(r.bolt, (bolts.get(r.bolt) || 0) + 1));
const low = rows.filter(r => r.confidence === 'check').length;
const yr = rows.reduce((a, r) => [Math.min(a[0], r.from), Math.max(a[1], r.to)], [9999, 0]);

console.log(`  ${rows.length} entries · ${makes.size} makes · ${yr[0]}-${yr[1]}`);
console.log(`  ${rows.length - low} high confidence, ${low} marked "check"`);
console.log('  patterns: ' + [...bolts.entries()].sort((a, b) => b[1] - a[1])
  .map(([b, n]) => `${b}(${n})`).join(' '));
console.log(`  wrote ${path.relative(ROOT, OUT)}`);
